name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - run: npm install -g pnpm@9

      - run: pnpm install

      - name: Build Frontend
        run: pnpm build

      - name: Build Rust
        working-directory: src-tauri
        run: cargo build --release -vv
